site_name: Lightweight Design Wiki
site_url: https://ldesign.readthedocs.io/en/latest/?badge=latest

theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/favicon.png
  language: en

repo_url: https://github.com/willi-z/ldesign
edit_uri: https://github.com/willi-z/ldesign/tree/main/docs
docs_dir: "docs"
site_dir: build/wiki


plugins:
    - search


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets

nav:
    - Einführung:
        - Home: README.md
        - Vorraussetzungen: getting-started.md
    - Material: 
        - Grundlagen: material/README.md
        - Eigenschaften: material/properties.md
        - Versagen: 
            - Übersicht: material/failure.md
            - Faserbruch: material/rupture.md
            - Delaminierung: material/delamination.md
        - RVEs: material/rve.md
    - Herstellung: 
        - Übersicht: manufacturing/README.md
        - Faserrichtung: manufacturing/direction.md
    - Konstruktion:
        - Grundlagen: design/README.md
        - Formen: design/geometry.md
        - Parametrisierung: design/parameterization.md
    - Simulation:
        - Grundlagen: simulation/README.md
        - Vernetzung: simulation/mesh.md
        - Optimierung: simulation/optimization.md
    - Software:
        - Übersicht: software/README.md
        - ANSYS:
            - Übersicht: software/ANSYS.md
            - SpaceClaim: software/ANSYS-SpaceClaim.md
            - "Material Designer": software/ANSYS-Material_Designer.md
            - "ACP": software/ANSYS-ACP(PRE).md
            - "Static Structural Analysis": software/ANSYS-StaticStructuralAnalysis.md
        - LS-DNYA:
            - Übersicht: software/LSDYNA.md
            - ANSYS-Module: software/LSDYNA-ANSYS.md
            - PREPOST: software/LSDYNA-PREPOST.md
    - Übungen:
        - "Erstellung eines Verbundwerkstoffes": examples/custom_material.md
        - "Versagen eines Faser": examples/fiber_falure.md
        - "Kugeleinschlag": examples/sphere_impact.md
        - "Parameterstudien": examples/parameter_studies.md
    - Quellen: references.md
    - About: about.md